"""机械臂抽象层：profile（能力描述）→ scene（装配）→ control（控制）→ kinematics（几何工具）。"""

from .control import RobotController, ServoResult
from .kinematics import (
    BOUNDED_TASK_ROTATION_RAD,
    BOUNDED_TASK_TRANSLATION_M,
    MAX_EDIT_ROTATION_RAD,
    MAX_EDIT_TRANSLATION_M,
    bounded_eef_target,
    bounded_task_error,
    edited_targets,
    matrix_to_quaternion_wxyz,
    pose,
    pose_from_arrays,
    preview_trajectory,
    quaternion_to_matrix,
    transform,
    validate_eef_target,
    validate_execution_contract,
    validate_public_language,
)
from .profile import ARM_PROFILES, ArmProfile, CameraMount, GripperSpec, get_profile, list_profiles
from .scene import (
    BuiltScene,
    SceneOptions,
    Slot,
    Workcell,
    build_scene,
    build_scene_xml,
    build_workcell,
    scale_stones,
)

__all__ = [
    "ARM_PROFILES",
    "ArmProfile",
    "BOUNDED_TASK_ROTATION_RAD",
    "BOUNDED_TASK_TRANSLATION_M",
    "BuiltScene",
    "CameraMount",
    "GripperSpec",
    "MAX_EDIT_ROTATION_RAD",
    "MAX_EDIT_TRANSLATION_M",
    "RobotController",
    "SceneOptions",
    "ServoResult",
    "Slot",
    "Workcell",
    "bounded_eef_target",
    "bounded_task_error",
    "build_scene",
    "build_scene_xml",
    "build_workcell",
    "edited_targets",
    "get_profile",
    "list_profiles",
    "matrix_to_quaternion_wxyz",
    "pose",
    "pose_from_arrays",
    "preview_trajectory",
    "quaternion_to_matrix",
    "scale_stones",
    "transform",
    "validate_eef_target",
    "validate_execution_contract",
    "validate_public_language",
]
